development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: oportunities
  pool: 5
  username: elogim
  password: elogim123 

test:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: oportunities_testP
  pool: 5
  username: elogim
  password: elogim123
